# Use a imagem base do Python
FROM python:3.13

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto para o diretório de trabalho
COPY . /app

# Instale as dependências
RUN pip install -r requirements.txt

# Defina a variável de ambiente
ENV FLASK_APP=run.py

# Exponha a porta 5000
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
